service: web-drumscore-scot

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-single-page-app-plugin

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1

custom:
  s3Bucket: ${opt:stage, self:provider.stage}.drumscore.scot

resources:
  Resources: ${file(serverless-${opt:stage, self:provider.stage}-resources.yml)}

  ## In order to print out the hosted domain via `serverless info` we need to define the DomainName output for CloudFormation
  Outputs:
    WebAppCloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [ WebAppCloudFrontDistribution, DomainName ]
